"""Project-wide constants used by the application skeleton."""

from chesslab.version import __version__

APP_NAME = "Chess Intelligence Laboratory"
APP_WINDOW_TITLE = f"{APP_NAME} - Stage 1"
CLI_DESCRIPTION = "Foundations of the Chess Intelligence Laboratory"
VERSION_STRING = __version__

DEFAULT_WINDOW_WIDTH = 1024
DEFAULT_WINDOW_HEIGHT = 768

BOARD_SIZE = 64
BOARD_FILES = "abcdefgh"
BOARD_RANKS = "12345678"
START_FEN_FIELD_COUNT = 6

WHITE_PAWN_START_RANK = 1
BLACK_PAWN_START_RANK = 6
WHITE_PROMOTION_RANK = 7
BLACK_PROMOTION_RANK = 0

HALFMOVE_CLOCK_DRAW_THRESHOLD = 100

WHITE_KINGSIDE_CASTLE_KING_FROM = 4   # e1
WHITE_KINGSIDE_CASTLE_KING_TO = 6     # g1
WHITE_KINGSIDE_CASTLE_ROOK_FROM = 7   # h1
WHITE_KINGSIDE_CASTLE_ROOK_TO = 5     # f1

WHITE_QUEENSIDE_CASTLE_KING_FROM = 4  # e1
WHITE_QUEENSIDE_CASTLE_KING_TO = 2    # c1
WHITE_QUEENSIDE_CASTLE_ROOK_FROM = 0  # a1
WHITE_QUEENSIDE_CASTLE_ROOK_TO = 3    # d1

BLACK_KINGSIDE_CASTLE_KING_FROM = 60  # e8
BLACK_KINGSIDE_CASTLE_KING_TO = 62    # g8
BLACK_KINGSIDE_CASTLE_ROOK_FROM = 63  # h8
BLACK_KINGSIDE_CASTLE_ROOK_TO = 61    # f8

BLACK_QUEENSIDE_CASTLE_KING_FROM = 60 # e8
BLACK_QUEENSIDE_CASTLE_KING_TO = 58   # c8
BLACK_QUEENSIDE_CASTLE_ROOK_FROM = 56 # a8
BLACK_QUEENSIDE_CASTLE_ROOK_TO = 59   # d8