"""Project-wide constants used by the application skeleton."""

from chesslab.version import __version__

APP_NAME = "Chess Intelligence Laboratory"
APP_WINDOW_TITLE = f"{APP_NAME} - Stage 1"
CLI_DESCRIPTION = "Foundations of the Chess Intelligence Laboratory"
VERSION_STRING = __version__

DEFAULT_WINDOW_WIDTH = 1024
DEFAULT_WINDOW_HEIGHT = 768

BOARD_SIZE = 64
BOARD_FILES = "abcdefgh"
BOARD_RANKS = "12345678"
START_FEN_FIELD_COUNT = 6

WHITE_PAWN_START_RANK = 1
BLACK_PAWN_START_RANK = 6
WHITE_PROMOTION_RANK = 7
BLACK_PROMOTION_RANK = 0

HALFMOVE_CLOCK_DRAW_THRESHOLD = 100

WHITE_KINGSIDE_CASTLE_KING_FROM = 4   # e1
WHITE_KINGSIDE_CASTLE_KING_TO = 6     # g1
WHITE_KINGSIDE_CASTLE_ROOK_FROM = 7   # h1
WHITE_KINGSIDE_CASTLE_ROOK_TO = 5     # f1

WHITE_QUEENSIDE_CASTLE_KING_FROM = 4  # e1
WHITE_QUEENSIDE_CASTLE_KING_TO = 2    # c1
WHITE_QUEENSIDE_CASTLE_ROOK_FROM = 0  # a1
WHITE_QUEENSIDE_CASTLE_ROOK_TO = 3    # d1

BLACK_KINGSIDE_CASTLE_KING_FROM = 60  # e8
BLACK_KINGSIDE_CASTLE_KING_TO = 62    # g8
BLACK_KINGSIDE_CASTLE_ROOK_FROM = 63  # h8
BLACK_KINGSIDE_CASTLE_ROOK_TO = 61    # f8

BLACK_QUEENSIDE_CASTLE_KING_FROM = 60 # e8
BLACK_QUEENSIDE_CASTLE_KING_TO = 58   # c8
BLACK_QUEENSIDE_CASTLE_ROOK_FROM = 56 # a8
BLACK_QUEENSIDE_CASTLE_ROOK_TO = 59   # d8

DEFAULT_SEARCH_DEPTH = 3
MATE_SCORE = 100000
DRAW_SCORE = 0

PAWN_VALUE = 100
KNIGHT_VALUE = 320
BISHOP_VALUE = 330
ROOK_VALUE = 500
QUEEN_VALUE = 900
KING_VALUE = 0

DEFAULT_MATERIAL_WEIGHT = 100
DEFAULT_MOBILITY_WEIGHT = 10
DEFAULT_KING_SAFETY_WEIGHT = 20
DEFAULT_PAWN_STRUCTURE_WEIGHT = 15
DEFAULT_CENTER_CONTROL_WEIGHT = 10
DEFAULT_PIECE_ACTIVITY_WEIGHT = 12

DOUBLED_PAWN_PENALTY = 10
ISOLATED_PAWN_PENALTY = 12

CENTER_OCCUPATION_BONUS = 12
CENTER_ATTACK_BONUS = 4

DEVELOPED_MINOR_PIECE_BONUS = 10
ADVANCED_KNIGHT_BONUS = 4
ADVANCED_BISHOP_BONUS = 4
ROOK_OPEN_FILE_BONUS = 10
ROOK_SEMIOPEN_FILE_BONUS = 5

KING_PAWN_SHIELD_BONUS = 8
KING_OPEN_FILE_PENALTY = 10
KING_NEARBY_ATTACK_PENALTY = 6
CASTLED_KING_BONUS = 10
UNCENTRALIZED_KING_ENDGAME_PENALTY = 0